#!/usr/bin/with-contenv sh
set -e

if [ -n ${RUN_ON_AWS} ]; then
    # Resolve the EC2 IP running a Consul Agent through API
    # We assume the port is the default one (8500)
    CONSUL_ADDRESS="$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4):8500"
fi

if [ -d /etc/consul-template/conf ]; then
  exec consul-template \
       -consul ${CONSUL_ADDRESS:-consul.service.consul:8500} \
       -config "/etc/consul-template/conf"
fi