FROM bandsintown/alpine:3.4

ENV BATS_VERSION=0.4.0

COPY tests /tests
WORKDIR /tests

RUN apk-install bind-tools bc \
    && curl -Ls https://codeload.github.com/sstephenson/bats/zip/v$BATS_VERSION -o /tmp/bats.zip \
	&& cd /tmp \
	&& unzip -q bats.zip \
	&& ./bats-${BATS_VERSION}/install.sh /usr/local \
	&& ln -sf /usr/local/libexec/bats /usr/local/bin/bats \
	&& rm -f bats.zip \
	&& mv /tests/consul-template/etc /etc/consul-template

CMD ["bash"]
